Add new screen
June22ai/weather_app pull request #5
Opened 2024-12-22 01:02 UTC by June22ai

最初の画面にある「次の画面」押下後、画面遷移。遷移先にある「戻る」ボタン押下後、遷移元画面に戻る。

https://github.com/user-attachments/assets/729baaac-3342-4804-8d23-47d6240cba35

2024-12-27 06:02 UTC, Kosuke-Ohashi commented on 7_Clima-iOS13/Clima/Controller/FavoreteViewController.swift
> +
上記コメントアウトされています！
不要な部分は削除ください。(13~17行目のメソッドは残しておいてください!)

2024-12-27 06:14 UTC, Kosuke-Ohashi commented on 7_Clima-iOS13/Clima/Controller/FavoreteViewController.swift
> +        if let navigationController = self.navigationController {
修正いただく必要はないのですが、今回Segueを使用していただいているのでナビゲーションコントローラーが呼ばれることはないです!

2024-12-27 06:14 UTC, Kosuke-Ohashi commented on 7_Clima-iOS13/Clima/Controller/FavoreteViewController.swift
> +
こちら48行目から56行目もコメントアウトされていておそらく不要かと思うので削除お願いいたします!

2024-12-27 06:16 UTC, Kosuke-Ohashi requested changes
遅くなってしまい申し訳ありません。
こちらレビューさせていただきましたのでご確認お願いいたします。

2024-12-28 23:46 UTC, June22ai commented
レビュー確認後修正しました。

2025-01-03 08:50 UTC, Kosuke-Ohashi approved these changes

2025-01-03 08:50 UTC, Kosuke-Ohashi commented
ご対応いただきありがとうございます!
こちら問題ないです!

2025-01-03 09:59 UTC, merged